### ISSUE TITLE
Create signup and login flow

### ISSUE THREAD

**Issue by Emeruem-Kennedy1** [Emeruem-Kennedy1/ghopper#1]
## Type
Feature

## Description
Implement Signup with Spotify

## Todo
- [x] Create User Database
- [x] Implement the UI and link that with the backend 
- [x] Store the user data for future login in the database (give the user a UUID)

## Notes

- Official documentation: https://developer.spotify.com/documentation/web-api/concepts/authorization
- Tutorial https://www.youtube.com/watch?v=olY_2MW4Eik

## Priority
High
