### ISSUE TITLE
Function to search for Search for a song using the Spotify api

### ISSUE THREAD

**Issue by Emeruem-Kennedy1** [Emeruem-Kennedy1/ghopper#17]
## Type
Feature, Enhancement

## Description

When we perform the song search, we get a bunch of songs and artists. We need to find the URLs for those songs on Spotify so that we can link to them in the front end. 

## Todo

- [x] Write a function to search Spotify for a song and artist combination
- [x] Write the best link that we found to the database so that we don't need to perform the search every time
- [x] return the song name, artists names, and link to the song. 

## Notes

#9 (App MVP that shows how we get a user's top songs and artists using the Spotify api)

## Priority
High
