### ISSUE TITLE
Create Profile Page

### ISSUE THREAD

**Issue by Emeruem-Kennedy1** [Emeruem-Kennedy1/ghopper#2]
## Type
Feature

## Description
Create the profile page to have the user image from Spotify with the user name and other details

## Todo
- [x] Modify the User model to store the user details
- [x] Fetch and store Data in the database for the user
- [x] Render User data on the Profile page in the frontend 
- [x] Design UI for the Profile page
- [x] Complete #1 

## Notes
- Official documentation https://developer.spotify.com/documentation/web-api/reference/get-users-top-artists-and-tracks

## Priority
High
