### ISSUE TITLE
Add Memoization to analysis requests

### ISSUE THREAD

**Issue by Emeruem-Kennedy1** [Emeruem-Kennedy1/ghopper#8]
## Type
Enhancement

## Description

When we send a request for analysis of a list of songs and depth (from the /search endpoint), we perform the analysis again for the same requests. We want to store the results for a particular song and retrieve it instead of performing the computation all over again. 

## Todo

- [ ] Create tables to store the results
     -  [ ] Key-Value pair of requests and results for a specific artist
- [ ] Store results for a given amount of time due to changing database
- [ ] Retrieve from the database on request, and if the result is not in the DB, we perform the BFS

## Notes

See #2 for the implementation of the BFS algorithm that performs the analysis

## Priority
High
